### ISSUE TITLE
User-Agent Switcher已经被报告是流氓插件了

### ISSUE THREAD

**Issue by Jailman** [jiang111/chrome-plugin-recommand#1]
User-Agent Switcher已经被查出是流氓插件了，读取图片中的代码来做一些不可告人的龌龊事，链接如下：
http://www.freebuf.com/news/147188.html
https://news.ycombinator.com/item?id=14889619

**Comment by jiang111** [comment]
User-Agent Switcher有2家，我贴的这个是官方的，你看到的那个是第三方的
